/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_sin;

import java.awt.image.BufferedImage;

/**
 *
 * @author Melany
 */
public class IUMostrar extends javax.swing.JFrame {
BufferedImage imagen;
    config config = new config();
    Esteganografia_clase esteganografia = new Esteganografia_clase();
    /**
     * Creates new form IUMostrar
     */
    public IUMostrar() {
        initComponents();
       this.setLocationRelativeTo(null);
       jPanel1.add(config);
       config.updateUI();
       this.BtnMostrarMensaje.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        BtnCargarImagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtMensaje = new javax.swing.JTextArea();
        BtnMostrarMensaje = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(764, 605));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOSTRAR MENSAJE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 22, 369, 55));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 130, -1));

        BtnVolver.setBackground(new java.awt.Color(0, 0, 255));
        BtnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        BtnCargarImagen.setBackground(new java.awt.Color(0, 153, 102));
        BtnCargarImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCargarImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargarImagen.setText("Cargar Imagen");
        BtnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(528, 328));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 520, 260));

        TxtMensaje.setColumns(20);
        TxtMensaje.setRows(5);
        jScrollPane3.setViewportView(TxtMensaje);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 470, 140));

        BtnMostrarMensaje.setBackground(new java.awt.Color(255, 153, 51));
        BtnMostrarMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnMostrarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        BtnMostrarMensaje.setText("Mostrar Mensaje");
        BtnMostrarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarMensajeActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background_1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed

        new Inicio().setVisible(true);
        dispose();

    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarImagenActionPerformed
if( config.Abrir_Imagen() ){   
         this.BtnMostrarMensaje.setEnabled(true);
        this.TxtMensaje.setText("");
        jPanel1.setPreferredSize(config.getTamanio());
        config.updateUI();
       }      }//GEN-LAST:event_BtnCargarImagenActionPerformed

    private void BtnMostrarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarMensajeActionPerformed
this.TxtMensaje.setText("");
this.TxtMensaje.setText(esteganografia.ExtraerBits(config.getFoto()));
    }//GEN-LAST:event_BtnMostrarMensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUMostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargarImagen;
    private javax.swing.JButton BtnMostrarMensaje;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextArea TxtMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
