/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_sin;

import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 *
 * @author Melany
 */
public class IUOcultar extends javax.swing.JFrame {
BufferedImage imagen;
    config config = new config();
    Esteganografia_clase esteganografia = new Esteganografia_clase();
    /**
     * Creates new form IUOcultar
     */
    public IUOcultar() {
       initComponents(); 
               this.setLocationRelativeTo(null);
       jPanel1.add(config);
       config.updateUI();
       this.BtnGuardarImagen.setEnabled(false);
       this.BtnOcultarTexto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCargarImagen = new javax.swing.JButton();
        BtnOcultarTexto = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BtnGuardarImagen = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtMensaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(771, 2147483647));
        setMinimumSize(new java.awt.Dimension(772, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OCULTAR MENSAJE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 369, 55));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 540, 270));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escriba el mensaje que desea ocultar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 380, -1));

        BtnCargarImagen.setBackground(new java.awt.Color(0, 153, 153));
        BtnCargarImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCargarImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargarImagen.setText("Cargar Imagen");
        BtnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 150, -1));

        BtnOcultarTexto.setBackground(new java.awt.Color(255, 153, 0));
        BtnOcultarTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnOcultarTexto.setForeground(new java.awt.Color(255, 255, 255));
        BtnOcultarTexto.setText("Ocultar mensaje");
        BtnOcultarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOcultarTextoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOcultarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 150, -1));

        BtnVolver.setBackground(new java.awt.Color(0, 51, 255));
        BtnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, -1));

        BtnGuardarImagen.setBackground(new java.awt.Color(102, 102, 255));
        BtnGuardarImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnGuardarImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarImagen.setText("Guardar Imagen");
        BtnGuardarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 150, -1));

        TxtMensaje.setColumns(20);
        TxtMensaje.setRows(5);
        jScrollPane3.setViewportView(TxtMensaje);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 471, 149));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background_1.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(772, 600));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -10, 780, 640));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarImagenActionPerformed
if( config.Abrir_Imagen() ){        
        this.BtnOcultarTexto.setEnabled(true);
        this.TxtMensaje.setText("");
        jPanel1.setPreferredSize(config.getTamanio());
        config.updateUI();
       }     }//GEN-LAST:event_BtnCargarImagenActionPerformed

    private void BtnGuardarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarImagenActionPerformed
config.guardar_imagen( esteganografia.getFoto() );
        BtnGuardarImagen.setEnabled(false);      }//GEN-LAST:event_BtnGuardarImagenActionPerformed

    private void BtnOcultarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOcultarTextoActionPerformed
//oculta el mensaje en la imagen
        esteganografia.OcultarTexto( config.getFoto(),TxtMensaje.getText() );        
        //vuelve a pintar la imagen en pantalla
        config.setFoto( esteganografia.getFoto()  );
        //deshabilita el boton
        BtnOcultarTexto.setEnabled(false);
        BtnGuardarImagen.setEnabled(true);
        JOptionPane.showMessageDialog(null, "El mensaje se oculto en la imagen");     }//GEN-LAST:event_BtnOcultarTextoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed

        new Inicio().setVisible(true);
        dispose();

    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUOcultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUOcultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUOcultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUOcultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUOcultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargarImagen;
    private javax.swing.JButton BtnGuardarImagen;
    private javax.swing.JButton BtnOcultarTexto;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextArea TxtMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
